package com.doks.conferencia.repository;

import java.time.LocalDate;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.doks.conferencia.model.AnaliseCompras2;

public interface AnaliseComprasRepository2 extends JpaRepository<AnaliseCompras2, Integer> {
	
	
	
@Query(value = "SELECT\r\n"
			
			+ " t1.id as id,"
		
		
			+ " t1.ean as ean,"
			+ "	t1.precoultimacompra AS precoultimacompra,\r\n"
			+ "	t1.codigo AS codigo,\r\n"
			+ "	t1.nome AS produto,\r\n"
			+ " t2.codigo as unidade_venda,"
		
	        + "(select sum(v1.quantidade) from vendas_itens_view v1 where v1.emissao >= ?5 and v1.emissao <= ?6 and v1.produto = t1.codigo and cast(v1.filial as INTEGER) = ?4 ) as quantidade_vendida,"
	        + "(select avg(v1.total) from vendas_itens_view v1 where v1.emissao >= ?5 and v1.emissao <= ?6 and v1.produto = t1.codigo and cast(v1.filial as INTEGER) = ?4 ) as preco_medio_venda,"
		
			+ "	t3.nome AS fornecedor,\r\n"
		
		
			
		
			+ "	(\r\n"
			+ "	SELECT SUM\r\n"
			+ "		( COALESCE ( quantidadesaldoestoquet1.quantidade, 0 ) ) \r\n"
			+ "	FROM\r\n"
			+ "		saldoestoque quantidadesaldoestoquet1 \r\n"
			+ "	WHERE\r\n"
			+ "		quantidadesaldoestoquet1.idfilial IN ( ?4 ) \r\n"
			+ "		AND quantidadesaldoestoquet1.idproduto = t1.ID \r\n"
			+ "		AND quantidadesaldoestoquet1.variacao = 0 \r\n"
			+ "	) AS saldo_estoque,\r\n"
			+ "	(\r\n"
			+ "	SELECT\r\n"
			+ "		quantidadeembalagemt1.fatorconversao \r\n"
			+ "	FROM\r\n"
			+ "		embalagem quantidadeembalagemt1 \r\n"
			+ "	WHERE\r\n"
			+ "		quantidadeembalagemt1.idproduto = t1.ID \r\n"
			+ "		AND quantidadeembalagemt1.tipoembalagem IN ( 1, 0 ) \r\n"
			+ "	ORDER BY\r\n"
			+ "		quantidadeembalagemt1.tipoembalagem DESC \r\n"
			+ "		LIMIT 1 \r\n"
			+ "	) AS embalagem,\r\n"
			+ "	(\r\n"
			+ "	SELECT\r\n"
			+ "		numeronfultcomprat3.numeronotafiscal \r\n"
			+ "	FROM\r\n"
			+ "		movimentoestoque numeronfultcomprat1\r\n"
			+ "		LEFT JOIN notafiscalitem numeronfultcomprat2 ON ( numeronfultcomprat2.ID = numeronfultcomprat1.iditemoriginal )\r\n"
			+ "		LEFT JOIN notafiscal numeronfultcomprat3 ON ( numeronfultcomprat3.ID = numeronfultcomprat2.idnotafiscal )\r\n"
			+ "		LEFT JOIN cfop numeronfultcomprat4 ON ( numeronfultcomprat4.ID = numeronfultcomprat3.idcfop ) \r\n"
			+ "	WHERE\r\n"
			+ "		numeronfultcomprat1.cancelado = 0 \r\n"
			+ "		AND numeronfultcomprat1.idproduto = t1.ID \r\n"
			+ "		AND numeronfultcomprat1.variacao = 0 \r\n"
			+ "		AND numeronfultcomprat1.idfilial IN ( ?4 ) \r\n"
			+ "		AND numeronfultcomprat1.tipodocumento = 2 \r\n"
			+ "		AND numeronfultcomprat1.quantidadeentrada > 0 \r\n"
			+ "		AND numeronfultcomprat4.consideracustomedio = 1 \r\n"
			+ "	ORDER BY\r\n"
			+ "		numeronfultcomprat1.datahora DESC \r\n"
			+ "		LIMIT 1 \r\n"
			+ "	) AS numeronfultcompra,\r\n"
			
	+ "	(SELECT\r\n"
	+ "		numeronfultcomprat3.datainclusao \r\n"
	+ "	FROM\r\n"
	+ "		movimentoestoque numeronfultcomprat1\r\n"
	+ "		LEFT JOIN notafiscalitem numeronfultcomprat2 ON ( numeronfultcomprat2.ID = numeronfultcomprat1.iditemoriginal )\r\n"
	+ "		LEFT JOIN notafiscal numeronfultcomprat3 ON ( numeronfultcomprat3.ID = numeronfultcomprat2.idnotafiscal )\r\n"
	+ "		LEFT JOIN cfop numeronfultcomprat4 ON ( numeronfultcomprat4.ID = numeronfultcomprat3.idcfop ) \r\n"
	+ "	WHERE\r\n"
	+ "		numeronfultcomprat1.cancelado = 0 \r\n"
	+ "		AND numeronfultcomprat1.idproduto = t1.ID \r\n"
	+ "		AND numeronfultcomprat1.variacao = 0 \r\n"
	+ "		AND numeronfultcomprat1.idfilial IN ( ?4 ) \r\n"
	+ "		AND numeronfultcomprat1.tipodocumento = 2 \r\n"
	+ "		AND numeronfultcomprat1.quantidadeentrada > 0 \r\n"
	+ "		AND numeronfultcomprat4.consideracustomedio = 1 \r\n"
	+ "	ORDER BY\r\n"
	+ "		numeronfultcomprat1.datahora DESC \r\n"
	+ "		LIMIT 1 \r\n"
	+ "	) AS data_inclusao,\r\n"
	
	
	+ "	(SELECT\r\n"
	+ "		numeronfultcomprat2.unidade \r\n"
	+ "	FROM\r\n"
	+ "		movimentoestoque numeronfultcomprat1\r\n"
	+ "		LEFT JOIN notafiscalitem numeronfultcomprat2 ON ( numeronfultcomprat2.ID = numeronfultcomprat1.iditemoriginal )\r\n"
	+ "		LEFT JOIN notafiscal numeronfultcomprat3 ON ( numeronfultcomprat3.ID = numeronfultcomprat2.idnotafiscal )\r\n"
	+ "		LEFT JOIN cfop numeronfultcomprat4 ON ( numeronfultcomprat4.ID = numeronfultcomprat3.idcfop ) \r\n"
	+ "	WHERE\r\n"
	+ "		numeronfultcomprat1.cancelado = 0 \r\n"
	+ "		AND numeronfultcomprat1.idproduto = t1.ID \r\n"
	+ "		AND numeronfultcomprat1.variacao = 0 \r\n"
	+ "		AND numeronfultcomprat1.idfilial IN ( ?4 ) \r\n"
	+ "		AND numeronfultcomprat1.tipodocumento = 2 \r\n"
	+ "		AND numeronfultcomprat1.quantidadeentrada > 0 \r\n"
	+ "		AND numeronfultcomprat4.consideracustomedio = 1 \r\n"
	+ "	ORDER BY\r\n"
	+ "		numeronfultcomprat1.datahora DESC \r\n"
	+ "		LIMIT 1 \r\n"
	+ "	) AS unidade_compra,\r\n"
	
	+ "	(SELECT\r\n"
	+ "		numeronfultcomprat4.codigo \r\n"
	+ "	FROM\r\n"
	+ "		movimentoestoque numeronfultcomprat1\r\n"
	+ "		LEFT JOIN notafiscalitem numeronfultcomprat2 ON ( numeronfultcomprat2.ID = numeronfultcomprat1.iditemoriginal )\r\n"
	+ "		LEFT JOIN notafiscal numeronfultcomprat3 ON ( numeronfultcomprat3.ID = numeronfultcomprat2.idnotafiscal )\r\n"
	+ "		LEFT JOIN cfop numeronfultcomprat4 ON ( numeronfultcomprat4.ID = numeronfultcomprat3.idcfop ) \r\n"
	+ "	WHERE\r\n"
	+ "		numeronfultcomprat1.cancelado = 0 \r\n"
	+ "		AND numeronfultcomprat1.idproduto = t1.ID \r\n"
	+ "		AND numeronfultcomprat1.variacao = 0 \r\n"
	+ "		AND numeronfultcomprat1.idfilial IN ( ?4 ) \r\n"
	+ "		AND numeronfultcomprat1.tipodocumento = 2 \r\n"
	+ "		AND numeronfultcomprat1.quantidadeentrada > 0 \r\n"
	+ "		AND numeronfultcomprat4.consideracustomedio = 1 \r\n"
	+ "	ORDER BY\r\n"
	+ "		numeronfultcomprat1.datahora DESC \r\n"
	+ "		LIMIT 1 \r\n"
	+ "	) AS cfop,\r\n"
			
			
			+ "	(\r\n"
			+ "	SELECT SUM\r\n"
			+ "		( COALESCE ( quantidadecomprat1.quantidadeentrada, 0 ) ) \r\n"
			+ "	FROM\r\n"
			+ "		movimentoestoque quantidadecomprat1\r\n"
			+ "		LEFT JOIN notafiscalitem quantidadecomprat2 ON ( quantidadecomprat2.ID = quantidadecomprat1.iditemoriginal )\r\n"
			+ "		LEFT JOIN notafiscal quantidadecomprat3 ON ( quantidadecomprat3.ID = quantidadecomprat2.idnotafiscal )\r\n"
			+ "		LEFT JOIN cfop quantidadecomprat4 ON ( quantidadecomprat4.ID = quantidadecomprat3.idcfop ) \r\n"
			+ "	WHERE\r\n"
			+ "		quantidadecomprat1.cancelado = 0 \r\n"
			+ "		AND quantidadecomprat1.idproduto = t1.ID \r\n"
			+ "		AND quantidadecomprat1.variacao = 0 \r\n"
			+ "		AND quantidadecomprat1.idfilial IN ( ?4 ) \r\n"
			+ "		AND quantidadecomprat1.tipodocumento = 2 \r\n"
			+ "		AND quantidadecomprat1.quantidadeentrada > 0 \r\n"
			+ "		AND quantidadecomprat4.consideracustomedio = 1 \r\n"
			+ "		AND quantidadecomprat1.datahora >= ?1 \r\n"
			+ "		AND quantidadecomprat1.datahora <= ?2 \r\n"
			+ "	) AS quantidade_comprada,\r\n"
			+ "	COALESCE (\r\n"
			+ "		(\r\n"
			+ "		SELECT\r\n"
			+ "			precoultimacomprat1.precoultimacompra \r\n"
			+ "		FROM\r\n"
			+ "			movimentoestoque precoultimacomprat1\r\n"
			+ "			LEFT JOIN notafiscalitem precoultimacomprat2 ON ( precoultimacomprat2.ID = precoultimacomprat1.iditemoriginal )\r\n"
			+ "			LEFT JOIN notafiscal precoultimacomprat3 ON ( precoultimacomprat3.ID = precoultimacomprat2.idnotafiscal )\r\n"
			+ "			LEFT JOIN cfop precoultimacomprat4 ON ( precoultimacomprat4.ID = precoultimacomprat3.idcfop ) \r\n"
			+ "		WHERE\r\n"
			+ "			precoultimacomprat1.cancelado = 0 \r\n"
			+ "			AND precoultimacomprat1.idproduto = t1.ID \r\n"
			+ "			AND precoultimacomprat1.variacao = 0 \r\n"
			+ "			AND precoultimacomprat1.idfilial IN ( ?4 ) \r\n"
			+ "			AND precoultimacomprat1.tipodocumento = 2 \r\n"
			+ "			AND precoultimacomprat1.quantidadeentrada > 0 \r\n"
			+ "			AND precoultimacomprat4.consideracustomedio = 1 \r\n"
			+ "		ORDER BY\r\n"
			+ "			precoultimacomprat1.datahora DESC \r\n"
			+ "			LIMIT 1 \r\n"
			+ "		),\r\n"
			+ "		t1.precoultimacompra \r\n"
			+ "	) AS ultimoprecocompra,\r\n"
			+ "	t1.precocusto AS custo_unitario,\r\n"
			+ "	t1.customedio AS customedio\r\n"
			
			+ "FROM\r\n"
			+ "	produto t1\r\n"
			+ "	LEFT JOIN unidademedida t2 ON ( t2.ID = t1.idunidademedida )\r\n"
			+ "	LEFT JOIN entidade t3 ON ( t3.ID = t1.idfornecedor )\r\n"
			+ "	LEFT JOIN hierarquia t4 ON ( t4.ID = t1.idhierarquia )\r\n"
			+ "	LEFT JOIN familiaproduto t5 ON ( t5.ID = t1.idfamilia ) \r\n"
			+ "WHERE\r\n"
			+ "	t1.inativo = 0 \r\n"
			+ "	AND t1.tipo = 'P' \r\n"
			+ "	AND t1.idfornecedor = ?3 ORDER BY quantidade_vendida desc ", nativeQuery = true)
           List<AnaliseCompras2> comprasProdutos(LocalDate dataI, LocalDate dataF, Integer fornecedor, Integer filial, LocalDate dataIV, LocalDate dataFV);

}
